# Generated by Django 3.0.3 on 2020-08-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_imported', models.PositiveIntegerField()),
                ('num_dormitories', models.PositiveIntegerField()),
                ('num_community', models.PositiveIntegerField()),
                ('num_new_cases', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
