# Generated by Django 3.0.3 on 2020-08-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
