# Generated by Django 3.0.3 on 2020-08-07 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200807_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='num_new_cases',
        ),
    ]
